package entity

// Code generated by xo. DO NOT EDIT.

import (
	"time"
)

// MPlantCotegory represents a row from 'public.m_plant_cotegory'.
type MPlantCategory struct {
	PlantCotegoryID   int       `json:"plant_cotegory_id"`   // plant_cotegory_id
	PlantCotegoryName string    `json:"plant_cotegory_name"` // plant_cotegory_name
	DeleteFlg         bool      `json:"delete_flg"`          // delete_flg
	CreateUser        string    `json:"create_user"`         // create_user
	CreateDatetime    time.Time `json:"create_datetime"`     // create_datetime
	UpdateUser        string    `json:"update_user"`         // update_user
	UpdateDatetime    time.Time `json:"update_datetime"`     // update_datetime
	Version           int       `json:"version"`             // version
}
