package entity

// Code generated by xo. DO NOT EDIT.

import (
	"time"
)

// MPlantcategory represents a row from 'public.m_plant_category'.
type MPlantCategory struct {
	PlantcategoryID   int       `json:"plant_category_id"`   // plant_category_id
	PlantcategoryName string    `json:"plant_category_name"` // plant_category_name
	DeleteFlg         bool      `json:"delete_flg"`          // delete_flg
	CreateUser        string    `json:"create_user"`         // create_user
	CreateDatetime    time.Time `json:"create_datetime"`     // create_datetime
	UpdateUser        string    `json:"update_user"`         // update_user
	UpdateDatetime    time.Time `json:"update_datetime"`     // update_datetime
	Version           int       `json:"version"`             // version
}
