package entity

// Code generated by xo. DO NOT EDIT.

import (
	"time"
)

// MSeason represents a row from 'public.m_season'.
type MSeason struct {
	SeasonID       int       `json:"season_id"`       // season_id
	SeasonName     string    `json:"season_name"`     // season_name
	DeleteFlg      bool      `json:"delete_flg"`      // delete_flg
	CreateUser     string    `json:"create_user"`     // create_user
	CreateDatetime time.Time `json:"create_datetime"` // create_datetime
	UpdateUser     string    `json:"update_user"`     // update_user
	UpdateDatetime time.Time `json:"update_datetime"` // update_datetime
	Version        int       `json:"version"`         // version
}
