package entity

// Code generated by xo. DO NOT EDIT.

import (
	"time"
)

// MVitalizer represents a row from 'public.m_vitalizer'.
type MVitalizer struct {
	VitalizerID    int       `json:"vitalizer_id"`    // vitalizer_id
	VitalizerName  string    `json:"vitalizer_name"`  // vitalizer_name
	DeleteFlg      bool      `json:"delete_flg"`      // delete_flg
	CreateUser     string    `json:"create_user"`     // create_user
	CreateDatetime time.Time `json:"create_datetime"` // create_datetime
	UpdateUser     string    `json:"update_user"`     // update_user
	UpdateDatetime time.Time `json:"update_datetime"` // update_datetime
	Version        int       `json:"version"`         // version
}
